// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.187
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.ExtensibilityTools
{
    static class Vsix
    {
        public const string Id = "f8330d54-0469-43a7-8fc0-7f19febeb897";
        public const string Name = "Extensibility Tools";
        public const string Description = @"Contains numerous tools and helpers that makes it easier than ever to build Visual Studio extensions.";
        public const string Language = "en-US";
        public const string Version = "1.10";
        public const string Author = "Mads Kristensen";
        public const string Tags = "VSIX, Extensibility, pkgdef, VSCT, Snippets, Encoding, Classification, ContentType, KnownMonikers";
    }
}
